### PR TITLE
Use TM2 will-save callback instead of did-save.

### PR DESCRIPTION
**Pull request by jakubpawlowicz**
- It's one save less!

### CODE REVIEW

**Comment by socrates** [comment]
_bump_ :)

I've actually tried the original bundle but it wasn't working, so tried the fork and it does the job. Can we have this merged or is there any technical reason for not wanting it?

**Comment by whatbird** [comment]
+1 on this

@jakubpawlowicz thanks

@ben5516 yup

**Comment by rmens** [comment]
Please merge this @adamjspooner

**Comment by adamjspooner** [comment]
Wow. I have no idea how I missed this PR. I'm sorry!

**Comment by jakubpawlowicz** [comment]
Thanks for merging! 💥

**Pull request merged**
